CREATE TABLE IF NOT EXISTS cities
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    state_id INTEGER  NOT NULL 
        references states (id)
);


INSERT INTO cities(name,state_id) VALUES ('Minneapolis',31);
INSERT INTO cities(name,state_id) VALUES ('Louisville',44);
INSERT INTO cities(name,state_id) VALUES ('Framingham',46);
INSERT INTO cities(name,state_id) VALUES ('San Diego',13);
INSERT INTO cities(name,state_id) VALUES ('San Francisco',43);
INSERT INTO cities(name,state_id) VALUES ('Charleston',3);
INSERT INTO cities(name,state_id) VALUES ('Denver',26);
INSERT INTO cities(name,state_id) VALUES ('Bridgman',47);
INSERT INTO cities(name,state_id) VALUES ('Holland',25);
INSERT INTO cities(name,state_id) VALUES ('Grand Rapids',7);
INSERT INTO cities(name,state_id) VALUES ('Grand Rapids',32);
INSERT INTO cities(name,state_id) VALUES ('Petoskey',20);
INSERT INTO cities(name,state_id) VALUES ('Marquette',35);
INSERT INTO cities(name,state_id) VALUES ('Comstock Park',34);
INSERT INTO cities(name,state_id) VALUES ('South Lyon',31);
INSERT INTO cities(name,state_id) VALUES ('Grand Rapids',28);
INSERT INTO cities(name,state_id) VALUES ('Indianapolis',51);
INSERT INTO cities(name,state_id) VALUES ('Evansville',43);
INSERT INTO cities(name,state_id) VALUES ('Indianapolis',23);
INSERT INTO cities(name,state_id) VALUES ('Plainfield',19);
INSERT INTO cities(name,state_id) VALUES ('Granger',5);
INSERT INTO cities(name,state_id) VALUES ('Martinsville',30);
INSERT INTO cities(name,state_id) VALUES ('Valparaiso',2);
INSERT INTO cities(name,state_id) VALUES ('Indianapolis',3);
INSERT INTO cities(name,state_id) VALUES ('Michigan City',8);
INSERT INTO cities(name,state_id) VALUES ('Indianapolis',42);
INSERT INTO cities(name,state_id) VALUES ('Mishawaka',8);
INSERT INTO cities(name,state_id) VALUES ('Columbus',12);
INSERT INTO cities(name,state_id) VALUES ('Bargersville',22);
INSERT INTO cities(name,state_id) VALUES ('Seven Points',11);
INSERT INTO cities(name,state_id) VALUES ('Chandler',19);
INSERT INTO cities(name,state_id) VALUES ('Kansas City',27);
INSERT INTO cities(name,state_id) VALUES ('Stevens Point',39);
INSERT INTO cities(name,state_id) VALUES ('Torrance',2);
INSERT INTO cities(name,state_id) VALUES ('San Diego',42);
INSERT INTO cities(name,state_id) VALUES ('San Francisco',6);
INSERT INTO cities(name,state_id) VALUES ('Buellton',44);
INSERT INTO cities(name,state_id) VALUES ('Boulder',30);
INSERT INTO cities(name,state_id) VALUES ('Dripping Springs',42);
INSERT INTO cities(name,state_id) VALUES ('Kalamazoo',8);
INSERT INTO cities(name,state_id) VALUES ('Murphysboro',25);
INSERT INTO cities(name,state_id) VALUES ('East Fairfield',6);
INSERT INTO cities(name,state_id) VALUES ('Portland',39);
INSERT INTO cities(name,state_id) VALUES ('Export',17);
INSERT INTO cities(name,state_id) VALUES ('Chicago',28);
INSERT INTO cities(name,state_id) VALUES ('Manhattan',51);
INSERT INTO cities(name,state_id) VALUES ('Brooklyn',50);
INSERT INTO cities(name,state_id) VALUES ('Hooksett',52);
INSERT INTO cities(name,state_id) VALUES ('Paso Robles',21);
INSERT INTO cities(name,state_id) VALUES ('Atlanta',48);
INSERT INTO cities(name,state_id) VALUES ('Troutville',31);
INSERT INTO cities(name,state_id) VALUES ('Boulder',33);
INSERT INTO cities(name,state_id) VALUES ('Chicago',11);
INSERT INTO cities(name,state_id) VALUES ('Roseville',32);
INSERT INTO cities(name,state_id) VALUES ('Lombard',10);
INSERT INTO cities(name,state_id) VALUES ('Lemont',36);
INSERT INTO cities(name,state_id) VALUES ('Lyons',35);
INSERT INTO cities(name,state_id) VALUES ('Bloomington',26);
INSERT INTO cities(name,state_id) VALUES ('St. Paul',5);
INSERT INTO cities(name,state_id) VALUES ('Portage',44);
INSERT INTO cities(name,state_id) VALUES ('Saint Louis',7);
INSERT INTO cities(name,state_id) VALUES ('Brooklyn Center',26);
INSERT INTO cities(name,state_id) VALUES ('Louisville',43);
INSERT INTO cities(name,state_id) VALUES ('Edwards',48);
INSERT INTO cities(name,state_id) VALUES ('Chicago',10);
INSERT INTO cities(name,state_id) VALUES ('Chicago',47);
INSERT INTO cities(name,state_id) VALUES ('San Antonio',16);
INSERT INTO cities(name,state_id) VALUES ('St Petersburg',35);
INSERT INTO cities(name,state_id) VALUES ('Mt. Airy',20);
INSERT INTO cities(name,state_id) VALUES ('Boone',44);
INSERT INTO cities(name,state_id) VALUES ('Charlotte',48);
INSERT INTO cities(name,state_id) VALUES ('Baltimore',45);
INSERT INTO cities(name,state_id) VALUES ('Detroit',22);
INSERT INTO cities(name,state_id) VALUES ('Madison',46);
INSERT INTO cities(name,state_id) VALUES ('Warrenville',27);
INSERT INTO cities(name,state_id) VALUES ('Duluth',10);
INSERT INTO cities(name,state_id) VALUES ('Kalamazoo',4);
INSERT INTO cities(name,state_id) VALUES ('Austin',28);
INSERT INTO cities(name,state_id) VALUES ('San Francisco',47);
INSERT INTO cities(name,state_id) VALUES ('Sheridan',25);
INSERT INTO cities(name,state_id) VALUES ('Portland',9);
INSERT INTO cities(name,state_id) VALUES ('Denver',12);
INSERT INTO cities(name,state_id) VALUES ('Fort Collins',52);
INSERT INTO cities(name,state_id) VALUES ('Chico',41);
INSERT INTO cities(name,state_id) VALUES ('Houghton',22);
INSERT INTO cities(name,state_id) VALUES ('Traverse City',33);
INSERT INTO cities(name,state_id) VALUES ('Westerly',25);
INSERT INTO cities(name,state_id) VALUES ('Kirkwood',1);
INSERT INTO cities(name,state_id) VALUES ('Chicago',43);
INSERT INTO cities(name,state_id) VALUES ('East Windsor',12);
INSERT INTO cities(name,state_id) VALUES ('Wilkes-Barre',45);
INSERT INTO cities(name,state_id) VALUES ('Cincinnati',40);
INSERT INTO cities(name,state_id) VALUES ('Athens',45);
INSERT INTO cities(name,state_id) VALUES ('Cincinnati',19);
INSERT INTO cities(name,state_id) VALUES ('Dayton',36);
INSERT INTO cities(name,state_id) VALUES ('Marquette',44);
INSERT INTO cities(name,state_id) VALUES ('Morganton',11);
INSERT INTO cities(name,state_id) VALUES ('Hershey',23);
INSERT INTO cities(name,state_id) VALUES ('San Diego',50);
INSERT INTO cities(name,state_id) VALUES ('Cincinnati',47);
INSERT INTO cities(name,state_id) VALUES ('Lexington',7);
INSERT INTO cities(name,state_id) VALUES ('Newport',24);
INSERT INTO cities(name,state_id) VALUES ('Anchorage',25);
INSERT INTO cities(name,state_id) VALUES ('Lowell',42);
INSERT INTO cities(name,state_id) VALUES ('Lone Tree',41);
INSERT INTO cities(name,state_id) VALUES ('Columbus',31);
INSERT INTO cities(name,state_id) VALUES ('Pineland',52);
INSERT INTO cities(name,state_id) VALUES ('Eagle',31);
INSERT INTO cities(name,state_id) VALUES ('Bloomfield',52);
INSERT INTO cities(name,state_id) VALUES ('North Woodstock',42);
INSERT INTO cities(name,state_id) VALUES ('Denver',1);
INSERT INTO cities(name,state_id) VALUES ('Vista',19);
INSERT INTO cities(name,state_id) VALUES ('Temecula',44);
INSERT INTO cities(name,state_id) VALUES ('Yardley',10);
INSERT INTO cities(name,state_id) VALUES ('Laurel',29);
INSERT INTO cities(name,state_id) VALUES ('Norfolk',49);
INSERT INTO cities(name,state_id) VALUES ('Portland',7);
INSERT INTO cities(name,state_id) VALUES ('Portland',25);
INSERT INTO cities(name,state_id) VALUES ('Conroe',42);
INSERT INTO cities(name,state_id) VALUES ('Durango',20);
INSERT INTO cities(name,state_id) VALUES ('Milwaukee',31);
INSERT INTO cities(name,state_id) VALUES ('Cheboygan',5);
INSERT INTO cities(name,state_id) VALUES ('Ashland',13);
INSERT INTO cities(name,state_id) VALUES ('Ipswich',48);
INSERT INTO cities(name,state_id) VALUES ('Birmingham',32);
INSERT INTO cities(name,state_id) VALUES ('Houston',50);
INSERT INTO cities(name,state_id) VALUES ('Austin',38);
INSERT INTO cities(name,state_id) VALUES ('Dallas',49);
INSERT INTO cities(name,state_id) VALUES ('Blanco',3);
INSERT INTO cities(name,state_id) VALUES ('St Mary''s',42);
INSERT INTO cities(name,state_id) VALUES ('Wolcott',16);
INSERT INTO cities(name,state_id) VALUES ('Stevens Point',16);
INSERT INTO cities(name,state_id) VALUES ('Weston',14);
INSERT INTO cities(name,state_id) VALUES ('Hattiesburg',45);
INSERT INTO cities(name,state_id) VALUES ('Monroe',23);
INSERT INTO cities(name,state_id) VALUES ('Dillon',33);
INSERT INTO cities(name,state_id) VALUES ('Austin',10);
INSERT INTO cities(name,state_id) VALUES ('Ada',44);
INSERT INTO cities(name,state_id) VALUES ('St Paul',18);
INSERT INTO cities(name,state_id) VALUES ('Springdale',37);
INSERT INTO cities(name,state_id) VALUES ('Austin',33);
INSERT INTO cities(name,state_id) VALUES ('Tampa',34);
INSERT INTO cities(name,state_id) VALUES ('Cold Spring',30);
INSERT INTO cities(name,state_id) VALUES ('Providence',15);
INSERT INTO cities(name,state_id) VALUES ('Loveland',14);
INSERT INTO cities(name,state_id) VALUES ('Nantucket',28);
INSERT INTO cities(name,state_id) VALUES ('Hayward',34);
INSERT INTO cities(name,state_id) VALUES ('Cleveland',44);
INSERT INTO cities(name,state_id) VALUES ('Arvada',46);
INSERT INTO cities(name,state_id) VALUES ('Raleigh',35);
INSERT INTO cities(name,state_id) VALUES ('Eugene',1);
INSERT INTO cities(name,state_id) VALUES ('Latrobe',15);
INSERT INTO cities(name,state_id) VALUES ('Baton Rouge',22);
INSERT INTO cities(name,state_id) VALUES ('Sisters',49);
INSERT INTO cities(name,state_id) VALUES ('Corvallis',22);
INSERT INTO cities(name,state_id) VALUES ('Ashland',6);
INSERT INTO cities(name,state_id) VALUES ('Lewisburg',44);
INSERT INTO cities(name,state_id) VALUES ('Phoenix',12);
INSERT INTO cities(name,state_id) VALUES ('Flagstaff',39);
INSERT INTO cities(name,state_id) VALUES ('Salt Lake City',29);
INSERT INTO cities(name,state_id) VALUES ('Tempe',18);
INSERT INTO cities(name,state_id) VALUES ('Fort Worth',36);
INSERT INTO cities(name,state_id) VALUES ('Traverse City',40);
INSERT INTO cities(name,state_id) VALUES ('Phoenixville',28);
INSERT INTO cities(name,state_id) VALUES ('Lansdale',35);
INSERT INTO cities(name,state_id) VALUES ('Aurora',35);
INSERT INTO cities(name,state_id) VALUES ('Longmont',38);
INSERT INTO cities(name,state_id) VALUES ('West Chester',20);
INSERT INTO cities(name,state_id) VALUES ('Windsor',46);
INSERT INTO cities(name,state_id) VALUES ('Garden City',10);
INSERT INTO cities(name,state_id) VALUES ('White Salmon',2);
INSERT INTO cities(name,state_id) VALUES ('Boonville',33);
INSERT INTO cities(name,state_id) VALUES ('Shelburne',7);
INSERT INTO cities(name,state_id) VALUES ('Brooklyn',6);
INSERT INTO cities(name,state_id) VALUES ('New Orleans',23);
INSERT INTO cities(name,state_id) VALUES ('Chicago',42);
INSERT INTO cities(name,state_id) VALUES ('Fort Worth',16);
INSERT INTO cities(name,state_id) VALUES ('Gary',23);
INSERT INTO cities(name,state_id) VALUES ('Cambridge',3);
INSERT INTO cities(name,state_id) VALUES ('Pittsboro',42);
INSERT INTO cities(name,state_id) VALUES ('Waynesville',17);
INSERT INTO cities(name,state_id) VALUES ('Nellysford',31);
INSERT INTO cities(name,state_id) VALUES ('Oklahoma City',6);
INSERT INTO cities(name,state_id) VALUES ('Columbus',44);
INSERT INTO cities(name,state_id) VALUES ('Austin',50);
INSERT INTO cities(name,state_id) VALUES ('Spring Lake',23);
INSERT INTO cities(name,state_id) VALUES ('Paw Paw',11);
INSERT INTO cities(name,state_id) VALUES ('Fredericksburg',50);
INSERT INTO cities(name,state_id) VALUES ('Springfield',21);
INSERT INTO cities(name,state_id) VALUES ('Lincoln',32);
INSERT INTO cities(name,state_id) VALUES ('Seattle',12);
INSERT INTO cities(name,state_id) VALUES ('Jackson',40);
INSERT INTO cities(name,state_id) VALUES ('Middleton',20);
INSERT INTO cities(name,state_id) VALUES ('Oklahoma City',44);
INSERT INTO cities(name,state_id) VALUES ('Bend',25);
INSERT INTO cities(name,state_id) VALUES ('Portland',47);
INSERT INTO cities(name,state_id) VALUES ('Chicago',49);
INSERT INTO cities(name,state_id) VALUES ('Portland',1);
INSERT INTO cities(name,state_id) VALUES ('Springfield',35);
INSERT INTO cities(name,state_id) VALUES ('Bend',51);
INSERT INTO cities(name,state_id) VALUES ('Portland',11);
INSERT INTO cities(name,state_id) VALUES ('Estacada',3);
INSERT INTO cities(name,state_id) VALUES ('Bloomington',17);
INSERT INTO cities(name,state_id) VALUES ('Hilo',25);
INSERT INTO cities(name,state_id) VALUES ('Hilo',12);
INSERT INTO cities(name,state_id) VALUES ('Lafayette',39);
INSERT INTO cities(name,state_id) VALUES ('Astoria',40);
INSERT INTO cities(name,state_id) VALUES ('San Antonio',17);
INSERT INTO cities(name,state_id) VALUES ('Kalona',45);
INSERT INTO cities(name,state_id) VALUES ('San Diego',40);
INSERT INTO cities(name,state_id) VALUES ('Evanston',1);
INSERT INTO cities(name,state_id) VALUES ('Verona',22);
INSERT INTO cities(name,state_id) VALUES ('Spearfish',49);
INSERT INTO cities(name,state_id) VALUES ('Farmers Branch',38);
INSERT INTO cities(name,state_id) VALUES ('Houston',9);
INSERT INTO cities(name,state_id) VALUES ('Richmond',46);
INSERT INTO cities(name,state_id) VALUES ('Atlanta',11);
INSERT INTO cities(name,state_id) VALUES ('Cherry Hill',16);
INSERT INTO cities(name,state_id) VALUES ('Ponderay',8);
INSERT INTO cities(name,state_id) VALUES ('Bozeman',43);
INSERT INTO cities(name,state_id) VALUES ('Broomfield',50);
INSERT INTO cities(name,state_id) VALUES ('Odessa',18);
INSERT INTO cities(name,state_id) VALUES ('Atlantic Highlands',47);
INSERT INTO cities(name,state_id) VALUES ('Anchorage',24);
INSERT INTO cities(name,state_id) VALUES ('Middleburg Heights',34);
INSERT INTO cities(name,state_id) VALUES ('Temecula',2);
INSERT INTO cities(name,state_id) VALUES ('Chatham',30);
INSERT INTO cities(name,state_id) VALUES ('Washington',2);
INSERT INTO cities(name,state_id) VALUES ('Lake Geneva',14);
INSERT INTO cities(name,state_id) VALUES ('Rochester',21);
INSERT INTO cities(name,state_id) VALUES ('Gloucester',13);
INSERT INTO cities(name,state_id) VALUES ('Tucson',7);
INSERT INTO cities(name,state_id) VALUES ('Lake Havasu City',50);
INSERT INTO cities(name,state_id) VALUES ('Henderson',28);
INSERT INTO cities(name,state_id) VALUES ('Boston',35);
INSERT INTO cities(name,state_id) VALUES ('Bloomfield',3);
INSERT INTO cities(name,state_id) VALUES ('Charlottesville',19);
INSERT INTO cities(name,state_id) VALUES ('Lexington',14);
INSERT INTO cities(name,state_id) VALUES ('Newburgh',36);
INSERT INTO cities(name,state_id) VALUES ('Memphis',49);
INSERT INTO cities(name,state_id) VALUES ('Los Angeles',37);
INSERT INTO cities(name,state_id) VALUES ('College Station',28);
INSERT INTO cities(name,state_id) VALUES ('Austin',11);
INSERT INTO cities(name,state_id) VALUES ('Plant City',51);
INSERT INTO cities(name,state_id) VALUES ('Stillwater',51);
INSERT INTO cities(name,state_id) VALUES ('Jackson',18);
INSERT INTO cities(name,state_id) VALUES ('Greenville',42);
INSERT INTO cities(name,state_id) VALUES ('Athens',34);
INSERT INTO cities(name,state_id) VALUES ('Stamford',5);
INSERT INTO cities(name,state_id) VALUES ('Southampton',28);
INSERT INTO cities(name,state_id) VALUES ('Angola',16);
INSERT INTO cities(name,state_id) VALUES ('Tucson',52);
INSERT INTO cities(name,state_id) VALUES ('Santa Cruz',29);
INSERT INTO cities(name,state_id) VALUES ('Frankenmuth',24);
INSERT INTO cities(name,state_id) VALUES ('Somerset Center',45);
INSERT INTO cities(name,state_id) VALUES ('Baltimore',22);
INSERT INTO cities(name,state_id) VALUES ('Chicago',32);
INSERT INTO cities(name,state_id) VALUES ('South Austin',9);
INSERT INTO cities(name,state_id) VALUES ('Minneapolis',16);
INSERT INTO cities(name,state_id) VALUES ('Rogers',52);
INSERT INTO cities(name,state_id) VALUES ('Mount Pleasant',41);
INSERT INTO cities(name,state_id) VALUES ('Waterbury',33);
INSERT INTO cities(name,state_id) VALUES ('Baltimore',42);
INSERT INTO cities(name,state_id) VALUES ('Denver',44);
INSERT INTO cities(name,state_id) VALUES ('Durango',23);
INSERT INTO cities(name,state_id) VALUES ('Albuquerque',40);
INSERT INTO cities(name,state_id) VALUES ('Portland',40);
INSERT INTO cities(name,state_id) VALUES ('Hyannis',27);
INSERT INTO cities(name,state_id) VALUES ('Bridgewater Corners',22);
INSERT INTO cities(name,state_id) VALUES ('Shreveport',12);
INSERT INTO cities(name,state_id) VALUES ('Juneau',14);
INSERT INTO cities(name,state_id) VALUES ('Ipswich',32);
INSERT INTO cities(name,state_id) VALUES ('Waterbury',48);
INSERT INTO cities(name,state_id) VALUES ('Charlottesville',25);
INSERT INTO cities(name,state_id) VALUES ('Cleveland',20);
INSERT INTO cities(name,state_id) VALUES ('Middlebury',14);
INSERT INTO cities(name,state_id) VALUES ('Montauk',18);
INSERT INTO cities(name,state_id) VALUES ('Minneapolis',48);
INSERT INTO cities(name,state_id) VALUES ('South Deerfield',11);
INSERT INTO cities(name,state_id) VALUES ('Pawtucket',21);
INSERT INTO cities(name,state_id) VALUES ('Mill Valley',44);
INSERT INTO cities(name,state_id) VALUES ('Ridgefield Park',18);
INSERT INTO cities(name,state_id) VALUES ('Kearney',13);
INSERT INTO cities(name,state_id) VALUES ('Hays',52);
INSERT INTO cities(name,state_id) VALUES ('Milwaukee',22);
INSERT INTO cities(name,state_id) VALUES ('Port Clinton',1);
INSERT INTO cities(name,state_id) VALUES ('Gadsden',12);
INSERT INTO cities(name,state_id) VALUES ('Dallas',52);
INSERT INTO cities(name,state_id) VALUES ('San Diego',14);
INSERT INTO cities(name,state_id) VALUES ('Newport',48);
INSERT INTO cities(name,state_id) VALUES ('Seattle',5);
INSERT INTO cities(name,state_id) VALUES ('Idaho Springs',30);
INSERT INTO cities(name,state_id) VALUES ('Lewiston',10);
INSERT INTO cities(name,state_id) VALUES ('Northamtpon',26);
INSERT INTO cities(name,state_id) VALUES ('Denver',40);
INSERT INTO cities(name,state_id) VALUES ('Westminster',5);
INSERT INTO cities(name,state_id) VALUES ('Portland',11);
INSERT INTO cities(name,state_id) VALUES ('Pittsburgh',21);
INSERT INTO cities(name,state_id) VALUES ('York',27);
INSERT INTO cities(name,state_id) VALUES ('Utica',5);
INSERT INTO cities(name,state_id) VALUES ('Boston',14);
INSERT INTO cities(name,state_id) VALUES ('Danville',29);
INSERT INTO cities(name,state_id) VALUES ('Salt Lake City',39);
INSERT INTO cities(name,state_id) VALUES ('South Burlington',28);
INSERT INTO cities(name,state_id) VALUES ('Canton',9);
INSERT INTO cities(name,state_id) VALUES ('Everett',42);
INSERT INTO cities(name,state_id) VALUES ('Virginia Beach',14);
INSERT INTO cities(name,state_id) VALUES ('Garden City',12);
INSERT INTO cities(name,state_id) VALUES ('Tampa',9);
INSERT INTO cities(name,state_id) VALUES ('Boise',28);
INSERT INTO cities(name,state_id) VALUES ('San Francisco',20);
INSERT INTO cities(name,state_id) VALUES ('Woodinville',50);
INSERT INTO cities(name,state_id) VALUES ('Nashville',33);
INSERT INTO cities(name,state_id) VALUES ('Meridian',14);
INSERT INTO cities(name,state_id) VALUES ('Bucryus',25);
INSERT INTO cities(name,state_id) VALUES ('Avon',20);
INSERT INTO cities(name,state_id) VALUES ('Wilmington',14);
INSERT INTO cities(name,state_id) VALUES ('Belfast',42);
INSERT INTO cities(name,state_id) VALUES ('Williamsburg',17);
INSERT INTO cities(name,state_id) VALUES ('Centralia',10);
INSERT INTO cities(name,state_id) VALUES ('Claremont',14);
INSERT INTO cities(name,state_id) VALUES ('Lockland',46);
INSERT INTO cities(name,state_id) VALUES ('Meadville',2);
INSERT INTO cities(name,state_id) VALUES ('Portland',36);
INSERT INTO cities(name,state_id) VALUES ('Black Mountain',8);
INSERT INTO cities(name,state_id) VALUES ('Croydon',25);
INSERT INTO cities(name,state_id) VALUES ('Saint Louis',30);
INSERT INTO cities(name,state_id) VALUES ('Chicago',47);
INSERT INTO cities(name,state_id) VALUES ('Burlington',38);
INSERT INTO cities(name,state_id) VALUES ('Bronx',4);
INSERT INTO cities(name,state_id) VALUES ('Tulsa',9);
INSERT INTO cities(name,state_id) VALUES ('Morganton',50);
INSERT INTO cities(name,state_id) VALUES ('Albuquerque',29);
INSERT INTO cities(name,state_id) VALUES ('Diamond Springs',36);
INSERT INTO cities(name,state_id) VALUES ('Burlington',17);
INSERT INTO cities(name,state_id) VALUES ('Fargo',6);
INSERT INTO cities(name,state_id) VALUES ('Missoula',46);
INSERT INTO cities(name,state_id) VALUES ('Papillion',43);
INSERT INTO cities(name,state_id) VALUES ('St. John''s',47);
INSERT INTO cities(name,state_id) VALUES ('Worcester',26);
INSERT INTO cities(name,state_id) VALUES ('Boynton Beach',3);
INSERT INTO cities(name,state_id) VALUES ('Palisade',50);
INSERT INTO cities(name,state_id) VALUES ('Brooklyn',35);
INSERT INTO cities(name,state_id) VALUES ('Richmond',28);
INSERT INTO cities(name,state_id) VALUES ('Abingdon',40);
INSERT INTO cities(name,state_id) VALUES ('Erie',13);
INSERT INTO cities(name,state_id) VALUES ('Santee',50);
INSERT INTO cities(name,state_id) VALUES ('Durham',28);
INSERT INTO cities(name,state_id) VALUES ('South Bend',10);
INSERT INTO cities(name,state_id) VALUES ('Green Bay',11);
INSERT INTO cities(name,state_id) VALUES ('San Luis Obispo',42);
INSERT INTO cities(name,state_id) VALUES ('Westfield',37);
INSERT INTO cities(name,state_id) VALUES ('Columbus',20);
INSERT INTO cities(name,state_id) VALUES ('Bellingham',48);
INSERT INTO cities(name,state_id) VALUES ('Bellingham',6);
INSERT INTO cities(name,state_id) VALUES ('Monument',10);
INSERT INTO cities(name,state_id) VALUES ('Philadelphia',24);
INSERT INTO cities(name,state_id) VALUES ('Cleveland',39);
INSERT INTO cities(name,state_id) VALUES ('Shelbyville',29);
INSERT INTO cities(name,state_id) VALUES ('Charlotte',10);
INSERT INTO cities(name,state_id) VALUES ('Fuquay-Varina',19);
INSERT INTO cities(name,state_id) VALUES ('Lake Barrington',30);
INSERT INTO cities(name,state_id) VALUES ('Seattle',24);
INSERT INTO cities(name,state_id) VALUES ('Pottstown',12);
INSERT INTO cities(name,state_id) VALUES ('Midvale',28);
INSERT INTO cities(name,state_id) VALUES ('Davenport',13);
INSERT INTO cities(name,state_id) VALUES ('Mustang',49);
INSERT INTO cities(name,state_id) VALUES ('Kent',18);
INSERT INTO cities(name,state_id) VALUES ('San Francisco',23);
INSERT INTO cities(name,state_id) VALUES ('Buena Vista',27);
INSERT INTO cities(name,state_id) VALUES ('Carlsbad',20);
INSERT INTO cities(name,state_id) VALUES ('Pottstown',51);
INSERT INTO cities(name,state_id) VALUES ('Conestoga',43);
INSERT INTO cities(name,state_id) VALUES ('Dunedin',36);
INSERT INTO cities(name,state_id) VALUES ('Astoria',40);
INSERT INTO cities(name,state_id) VALUES ('Lahaina',38);
INSERT INTO cities(name,state_id) VALUES ('Midwest City',1);
INSERT INTO cities(name,state_id) VALUES ('Menominee',11);
INSERT INTO cities(name,state_id) VALUES ('Jacksonville',40);
INSERT INTO cities(name,state_id) VALUES ('Westerly',12);
INSERT INTO cities(name,state_id) VALUES ('Lincoln',19);
INSERT INTO cities(name,state_id) VALUES ('Manheim',17);
INSERT INTO cities(name,state_id) VALUES ('Afton',16);
INSERT INTO cities(name,state_id) VALUES ('Crozet',6);
INSERT INTO cities(name,state_id) VALUES ('Mt. Pleasant',51);
INSERT INTO cities(name,state_id) VALUES ('Portland',36);
INSERT INTO cities(name,state_id) VALUES ('Paonia',41);
INSERT INTO cities(name,state_id) VALUES ('Portland',42);
INSERT INTO cities(name,state_id) VALUES ('Lexington',40);
INSERT INTO cities(name,state_id) VALUES ('Brevard',40);
INSERT INTO cities(name,state_id) VALUES ('Airway Heights',24);
INSERT INTO cities(name,state_id) VALUES ('Denver',46);
INSERT INTO cities(name,state_id) VALUES ('Santa Fe',44);
INSERT INTO cities(name,state_id) VALUES ('Miami',23);
INSERT INTO cities(name,state_id) VALUES ('Seattle',35);
INSERT INTO cities(name,state_id) VALUES ('Austin',28);
INSERT INTO cities(name,state_id) VALUES ('Hudsonville',41);
INSERT INTO cities(name,state_id) VALUES ('Sacramento',7);
INSERT INTO cities(name,state_id) VALUES ('Douglas',32);
INSERT INTO cities(name,state_id) VALUES ('Moab',6);
INSERT INTO cities(name,state_id) VALUES ('Macon',10);
INSERT INTO cities(name,state_id) VALUES ('Washougal',25);
INSERT INTO cities(name,state_id) VALUES ('Ann Arbor',21);
INSERT INTO cities(name,state_id) VALUES ('Bend',22);
INSERT INTO cities(name,state_id) VALUES ('Portland',16);
INSERT INTO cities(name,state_id) VALUES ('Boulder',38);
INSERT INTO cities(name,state_id) VALUES ('Eau Claire',49);
INSERT INTO cities(name,state_id) VALUES ('Hamilton',6);
INSERT INTO cities(name,state_id) VALUES ('Bend',29);
INSERT INTO cities(name,state_id) VALUES ('Lakeside',42);
INSERT INTO cities(name,state_id) VALUES ('Woodbridge',48);
INSERT INTO cities(name,state_id) VALUES ('Seattle',2);
INSERT INTO cities(name,state_id) VALUES ('Huntsville',26);
INSERT INTO cities(name,state_id) VALUES ('Austin',45);
INSERT INTO cities(name,state_id) VALUES ('Arrington',20);
INSERT INTO cities(name,state_id) VALUES ('Savannah',52);
INSERT INTO cities(name,state_id) VALUES ('Biglerville',48);
INSERT INTO cities(name,state_id) VALUES ('Boulder',22);
INSERT INTO cities(name,state_id) VALUES ('Portland',19);
INSERT INTO cities(name,state_id) VALUES ('Boulder',49);
INSERT INTO cities(name,state_id) VALUES ('Edwards',30);
INSERT INTO cities(name,state_id) VALUES ('Boulder',7);
INSERT INTO cities(name,state_id) VALUES ('Eugene',4);
INSERT INTO cities(name,state_id) VALUES ('San Diego',2);
INSERT INTO cities(name,state_id) VALUES ('Denver',16);
INSERT INTO cities(name,state_id) VALUES ('Stevens Point',38);
INSERT INTO cities(name,state_id) VALUES ('Denton',51);
INSERT INTO cities(name,state_id) VALUES ('Roanoke',7);
INSERT INTO cities(name,state_id) VALUES ('Saint Louis',18);
INSERT INTO cities(name,state_id) VALUES ('Boulder',26);
INSERT INTO cities(name,state_id) VALUES ('Ashburn',4);
INSERT INTO cities(name,state_id) VALUES ('Slippery Rock',33);
INSERT INTO cities(name,state_id) VALUES ('Santa Cruz',51);
INSERT INTO cities(name,state_id) VALUES ('Asheville',22);
INSERT INTO cities(name,state_id) VALUES ('Cincinnati',47);
INSERT INTO cities(name,state_id) VALUES ('Stratford',36);
INSERT INTO cities(name,state_id) VALUES ('Medford',30);
INSERT INTO cities(name,state_id) VALUES ('Brooklyn',11);
INSERT INTO cities(name,state_id) VALUES ('Traverse City',17);
INSERT INTO cities(name,state_id) VALUES ('Kona',29);
INSERT INTO cities(name,state_id) VALUES ('Royal Oak',43);
INSERT INTO cities(name,state_id) VALUES ('Fort Collins',24);
INSERT INTO cities(name,state_id) VALUES ('O''Fallon',29);
INSERT INTO cities(name,state_id) VALUES ('Albuquerque',44);
INSERT INTO cities(name,state_id) VALUES ('Vadnais Heights',21);
INSERT INTO cities(name,state_id) VALUES ('Lenoir',26);
INSERT INTO cities(name,state_id) VALUES ('Leominster',46);
INSERT INTO cities(name,state_id) VALUES ('Gainesville',48);
INSERT INTO cities(name,state_id) VALUES ('Half Moon Bay',37);
INSERT INTO cities(name,state_id) VALUES ('San Diego',35);
INSERT INTO cities(name,state_id) VALUES ('Pacific',24);
INSERT INTO cities(name,state_id) VALUES ('Aurora',6);
INSERT INTO cities(name,state_id) VALUES ('Edwards',27);
INSERT INTO cities(name,state_id) VALUES ('Talkeetna',43);
INSERT INTO cities(name,state_id) VALUES ('Bend',12);
INSERT INTO cities(name,state_id) VALUES ('Hardy',15);
INSERT INTO cities(name,state_id) VALUES ('Menominie',39);
INSERT INTO cities(name,state_id) VALUES ('Sheridan',35);
INSERT INTO cities(name,state_id) VALUES ('Soldotna',38);
INSERT INTO cities(name,state_id) VALUES ('Denver',49);
INSERT INTO cities(name,state_id) VALUES ('Seattle',14);
INSERT INTO cities(name,state_id) VALUES ('South San Francisco',35);
INSERT INTO cities(name,state_id) VALUES ('Golden',12);
INSERT INTO cities(name,state_id) VALUES ('Alpine',13);
INSERT INTO cities(name,state_id) VALUES ('Bend',28);
INSERT INTO cities(name,state_id) VALUES ('Jacksonville Beach',14);
INSERT INTO cities(name,state_id) VALUES ('Jacksonville',7);
INSERT INTO cities(name,state_id) VALUES ('Tampa Bay',31);
INSERT INTO cities(name,state_id) VALUES ('Knoxville',11);
INSERT INTO cities(name,state_id) VALUES ('Athens',6);
INSERT INTO cities(name,state_id) VALUES ('San Antonio',1);
INSERT INTO cities(name,state_id) VALUES ('Spirit Lake',24);
INSERT INTO cities(name,state_id) VALUES ('Boulder',14);
INSERT INTO cities(name,state_id) VALUES ('Tacoma',45);
INSERT INTO cities(name,state_id) VALUES ('Minnetonka',20);
INSERT INTO cities(name,state_id) VALUES ('Marietta',26);
INSERT INTO cities(name,state_id) VALUES ('Redlands',45);
INSERT INTO cities(name,state_id) VALUES ('Sheffield',51);
INSERT INTO cities(name,state_id) VALUES ('Birmingham',52);
INSERT INTO cities(name,state_id) VALUES ('Halethorpe',22);
INSERT INTO cities(name,state_id) VALUES ('Telluride',18);
INSERT INTO cities(name,state_id) VALUES ('Gig Harbor',34);
INSERT INTO cities(name,state_id) VALUES ('Des Moines',26);
INSERT INTO cities(name,state_id) VALUES ('Yakima',38);
INSERT INTO cities(name,state_id) VALUES ('New York',20);
INSERT INTO cities(name,state_id) VALUES ('Portland',8);
INSERT INTO cities(name,state_id) VALUES ('Green Bay',29);
INSERT INTO cities(name,state_id) VALUES ('Woodinville',42);
INSERT INTO cities(name,state_id) VALUES ('Philadelphia',43);
INSERT INTO cities(name,state_id) VALUES ('Patchogue',8);
INSERT INTO cities(name,state_id) VALUES ('Tampa',8);
INSERT INTO cities(name,state_id) VALUES ('Belmont',40);
INSERT INTO cities(name,state_id) VALUES ('Portland',44);
INSERT INTO cities(name,state_id) VALUES ('Anchorage',7);
INSERT INTO cities(name,state_id) VALUES ('Silverton',36);
INSERT INTO cities(name,state_id) VALUES ('Newburyport',12);
INSERT INTO cities(name,state_id) VALUES ('Aurora',37);
INSERT INTO cities(name,state_id) VALUES ('Charlotte',33);
INSERT INTO cities(name,state_id) VALUES ('Glendale',45);
INSERT INTO cities(name,state_id) VALUES ('Stevensville',40);
INSERT INTO cities(name,state_id) VALUES ('Leavenworth',41);
INSERT INTO cities(name,state_id) VALUES ('Middlebury',28);
INSERT INTO cities(name,state_id) VALUES ('Portland',8);
INSERT INTO cities(name,state_id) VALUES ('Lyons',30);
INSERT INTO cities(name,state_id) VALUES ('Mooresville',52);
INSERT INTO cities(name,state_id) VALUES ('Krebs',28);
INSERT INTO cities(name,state_id) VALUES ('Fort Wayne',51);
INSERT INTO cities(name,state_id) VALUES ('Lake Havasu City',45);
INSERT INTO cities(name,state_id) VALUES ('Cortland',21);
INSERT INTO cities(name,state_id) VALUES ('Tacoma',2);
INSERT INTO cities(name,state_id) VALUES ('Missoula',27);
INSERT INTO cities(name,state_id) VALUES ('Marlborough',32);
INSERT INTO cities(name,state_id) VALUES ('Pawcatuck',16);
INSERT INTO cities(name,state_id) VALUES ('Colorado Springs',4);
INSERT INTO cities(name,state_id) VALUES ('San Diego',40);
INSERT INTO cities(name,state_id) VALUES ('Greeley',40);
INSERT INTO cities(name,state_id) VALUES ('Seattle',5);
INSERT INTO cities(name,state_id) VALUES ('Carlsbad',31);
INSERT INTO cities(name,state_id) VALUES ('Myrtle Beach',52);
INSERT INTO cities(name,state_id) VALUES ('Chattanooga',24);
INSERT INTO cities(name,state_id) VALUES ('Boulder',20);
INSERT INTO cities(name,state_id) VALUES ('Frederick',20);
INSERT INTO cities(name,state_id) VALUES ('Santa Cruz',43);
INSERT INTO cities(name,state_id) VALUES ('Aspen',37);
INSERT INTO cities(name,state_id) VALUES ('Durham',43);
INSERT INTO cities(name,state_id) VALUES ('New York',27);
INSERT INTO cities(name,state_id) VALUES ('Seattle',20);
INSERT INTO cities(name,state_id) VALUES ('Jacksonville',27);
INSERT INTO cities(name,state_id) VALUES ('Asheville',50);
INSERT INTO cities(name,state_id) VALUES ('Eau Claire',18);
INSERT INTO cities(name,state_id) VALUES ('Reno',36);
INSERT INTO cities(name,state_id) VALUES ('Dolores',51);
INSERT INTO cities(name,state_id) VALUES ('Smithton',27);
INSERT INTO cities(name,state_id) VALUES ('Abita Springs',13);
INSERT INTO cities(name,state_id) VALUES ('Mammoth Lakes',36);
INSERT INTO cities(name,state_id) VALUES ('Belt',39);
INSERT INTO cities(name,state_id) VALUES ('Williams',32);
INSERT INTO cities(name,state_id) VALUES ('Helena',35);
INSERT INTO cities(name,state_id) VALUES ('Rochester',31);
INSERT INTO cities(name,state_id) VALUES ('Greenville',52);
INSERT INTO cities(name,state_id) VALUES ('Kinston',36);
INSERT INTO cities(name,state_id) VALUES ('Battle Creek',28);
INSERT INTO cities(name,state_id) VALUES ('Hayward',33);
INSERT INTO cities(name,state_id) VALUES ('Whitefish',20);
INSERT INTO cities(name,state_id) VALUES ('Seattle',37);
INSERT INTO cities(name,state_id) VALUES ('Lancaster',20);
INSERT INTO cities(name,state_id) VALUES ('Elmira',12);
INSERT INTO cities(name,state_id) VALUES ('North Conway',18);
INSERT INTO cities(name,state_id) VALUES ('Prescott',16);
INSERT INTO cities(name,state_id) VALUES ('Flagstaff',3);
INSERT INTO cities(name,state_id) VALUES ('Pinedale',20);
INSERT INTO cities(name,state_id) VALUES ('Silverton',8);
INSERT INTO cities(name,state_id) VALUES ('Libertyville',7);
INSERT INTO cities(name,state_id) VALUES ('Covington',22);
INSERT INTO cities(name,state_id) VALUES ('Wilson',15);
INSERT INTO cities(name,state_id) VALUES ('Ukiah',19);
INSERT INTO cities(name,state_id) VALUES ('Garrattsville',23);
INSERT INTO cities(name,state_id) VALUES ('Anchorage',17);