CREATE TABLE styles
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);


INSERT INTO styles(name) VALUES ('American Pale Lager');
INSERT INTO styles(name) VALUES ('American Pale Ale (APA)');
INSERT INTO styles(name) VALUES ('American IPA');
INSERT INTO styles(name) VALUES ('American Double / Imperial IPA');
INSERT INTO styles(name) VALUES ('Oatmeal Stout');
INSERT INTO styles(name) VALUES ('American Porter');
INSERT INTO styles(name) VALUES ('Saison / Farmhouse Ale');
INSERT INTO styles(name) VALUES ('Belgian IPA');
INSERT INTO styles(name) VALUES ('Cider');
INSERT INTO styles(name) VALUES ('Baltic Porter');
INSERT INTO styles(name) VALUES ('Tripel');
INSERT INTO styles(name) VALUES ('American Barleywine');
INSERT INTO styles(name) VALUES ('Winter Warmer');
INSERT INTO styles(name) VALUES ('American Stout');
INSERT INTO styles(name) VALUES ('Fruit / Vegetable Beer');
INSERT INTO styles(name) VALUES ('English Strong Ale');
INSERT INTO styles(name) VALUES ('American Black Ale');
INSERT INTO styles(name) VALUES ('Belgian Dark Ale');
INSERT INTO styles(name) VALUES ('American Blonde Ale');
INSERT INTO styles(name) VALUES ('American Amber / Red Ale');
INSERT INTO styles(name) VALUES ('Berliner Weissbier');
INSERT INTO styles(name) VALUES ('American Brown Ale');
INSERT INTO styles(name) VALUES ('American Pale Wheat Ale');
INSERT INTO styles(name) VALUES ('Belgian Strong Dark Ale');
INSERT INTO styles(name) VALUES ('Kölsch');
INSERT INTO styles(name) VALUES ('English Pale Ale');
INSERT INTO styles(name) VALUES ('American Amber / Red Lager');
INSERT INTO styles(name) VALUES ('English Barleywine');
INSERT INTO styles(name) VALUES ('Milk / Sweet Stout');
INSERT INTO styles(name) VALUES ('German Pilsener');
INSERT INTO styles(name) VALUES ('Pumpkin Ale');
INSERT INTO styles(name) VALUES ('Belgian Pale Ale');
INSERT INTO styles(name) VALUES ('American Pilsner');
INSERT INTO styles(name) VALUES ('American Wild Ale');
INSERT INTO styles(name) VALUES ('English Brown Ale');
INSERT INTO styles(name) VALUES ('Altbier');
INSERT INTO styles(name) VALUES ('California Common / Steam Beer');
INSERT INTO styles(name) VALUES ('Gose');
INSERT INTO styles(name) VALUES ('Cream Ale');
INSERT INTO styles(name) VALUES ('Vienna Lager');
INSERT INTO styles(name) VALUES ('Witbier');
INSERT INTO styles(name) VALUES ('American Double / Imperial Stout');
INSERT INTO styles(name) VALUES ('Munich Helles Lager');
INSERT INTO styles(name) VALUES ('Schwarzbier');
INSERT INTO styles(name) VALUES ('Märzen / Oktoberfest');
INSERT INTO styles(name) VALUES ('Extra Special / Strong Bitter (ESB)');
INSERT INTO styles(name) VALUES ('Rye Beer');
INSERT INTO styles(name) VALUES ('Euro Dark Lager');
INSERT INTO styles(name) VALUES ('Hefeweizen');
INSERT INTO styles(name) VALUES ('Foreign / Export Stout');
INSERT INTO styles(name) VALUES ('Other');
INSERT INTO styles(name) VALUES ('English India Pale Ale (IPA)');
INSERT INTO styles(name) VALUES ('Czech Pilsener');
INSERT INTO styles(name) VALUES ('American Strong Ale');
INSERT INTO styles(name) VALUES ('Mead');
INSERT INTO styles(name) VALUES ('Euro Pale Lager');
INSERT INTO styles(name) VALUES ('American White IPA');
INSERT INTO styles(name) VALUES ('Dortmunder / Export Lager');
INSERT INTO styles(name) VALUES ('Irish Dry Stout');
INSERT INTO styles(name) VALUES ('Scotch Ale / Wee Heavy');
INSERT INTO styles(name) VALUES ('Munich Dunkel Lager');
INSERT INTO styles(name) VALUES ('Radler');
INSERT INTO styles(name) VALUES ('Bock');
INSERT INTO styles(name) VALUES ('English Dark Mild Ale');
INSERT INTO styles(name) VALUES ('Irish Red Ale');
INSERT INTO styles(name) VALUES ('Rauchbier');
INSERT INTO styles(name) VALUES ('Bière de Garde');
INSERT INTO styles(name) VALUES ('Doppelbock');
INSERT INTO styles(name) VALUES ('Dunkelweizen');
INSERT INTO styles(name) VALUES ('Belgian Strong Pale Ale');
INSERT INTO styles(name) VALUES ('Dubbel');
INSERT INTO styles(name) VALUES ('Quadrupel (Quad)');
INSERT INTO styles(name) VALUES ('Russian Imperial Stout');
INSERT INTO styles(name) VALUES ('English Pale Mild Ale');
INSERT INTO styles(name) VALUES ('Maibock / Helles Bock');
INSERT INTO styles(name) VALUES ('Herbed / Spiced Beer');
INSERT INTO styles(name) VALUES ('American Adjunct Lager');
INSERT INTO styles(name) VALUES ('Scottish Ale');
INSERT INTO styles(name) VALUES ('Smoked Beer');
INSERT INTO styles(name) VALUES ('Light Lager');
INSERT INTO styles(name) VALUES ('Abbey Single Ale');
INSERT INTO styles(name) VALUES ('Roggenbier');
INSERT INTO styles(name) VALUES ('Kristalweizen');
INSERT INTO styles(name) VALUES ('American Dark Wheat Ale');
INSERT INTO styles(name) VALUES ('English Stout');
INSERT INTO styles(name) VALUES ('Old Ale');
INSERT INTO styles(name) VALUES ('American Double / Imperial Pilsner');
INSERT INTO styles(name) VALUES ('Flanders Red Ale');
INSERT INTO styles(name) VALUES ('Keller Bier / Zwickel Bier');
INSERT INTO styles(name) VALUES ('American India Pale Lager');
INSERT INTO styles(name) VALUES ('Shandy');
INSERT INTO styles(name) VALUES ('Wheat Ale');
INSERT INTO styles(name) VALUES ('American Malt Liquor');
INSERT INTO styles(name) VALUES ('English Bitter');
INSERT INTO styles(name) VALUES ('Chile Beer');
INSERT INTO styles(name) VALUES ('Grisette');
INSERT INTO styles(name) VALUES ('Flanders Oud Bruin');
INSERT INTO styles(name) VALUES ('Braggot');
INSERT INTO styles(name) VALUES ('Low Alcohol Beer');
