CREATE TABLE IF NOT EXISTS beer.breweries(
   id      INTEGER NOT NULL PRIMARY KEY,
   name    VARCHAR(100) NOT NULL,
   city_id INTEGER NOT NULL references beer.cities (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);
    SELECT beer.trigger_creation('beer','breweries','tr_b_breweries');
INSERT INTO beer.breweries(id,name,city_id) VALUES (1,'NorthGate Brewing',542) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (2,'Against the Grain Brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (3,'Jack''s Abby Craft Lagers',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (4,'Mike Hess Brewing Company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (5,'Fort Point Beer Company',251) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (6,'COAST Brewing Company',415) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (7,'Great Divide Brewing Company',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (8,'Tapistry Brewing',258) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (9,'Big Lake Brewing',391) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (10,'The Mitten Brewing Company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (11,'Brewery Vivant',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (12,'Petoskey Brewing',181) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (13,'Blackrocks Brewery',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (14,'Perrin Brewing Company',214) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (15,'Witch''s Hat Brewing Company',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (16,'Founders Brewing Company',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (17,'Flat 12 Bierwerks',382) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (18,'Tin Man Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (19,'Black Acre Brewing Co.',196) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (20,'Brew Link Brewing',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (21,'Bare Hands Brewery',279) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (22,'Three Pints Brewing',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (23,'Four Fathers Brewing',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (24,'Indiana City Brewing',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (25,'Burn ''Em Brewing',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (26,'Sun King Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (27,'Evil Czech Brewery',97) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (28,'450 North Brewing Company',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (29,'Taxman Brewing Company',150) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (30,'Cedar Creek Brewery',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (31,'SanTan Brewing Company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (32,'Boulevard Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (33,'James Page Brewing Company',325) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (34,'The Dudes'' Brewing Company',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (35,'Ballast Point Brewing Company',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (36,'Anchor Brewing Company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (37,'Figueroa Mountain Brewing Company',539) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (38,'Avery Brewing Company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (39,'Twisted X Brewing Company',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (40,'Gonzo''s BiggDogg Brewing',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (41,'Big Muddy Brewing',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (42,'Lost Nation Brewing',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (43,'Rising Tide Brewing Company',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (44,'Rivertowne Brewing Company',184) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (45,'Revolution Brewing Company',263) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (46,'Tallgrass Brewing Company',353) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (47,'Sixpoint Craft Ales',122) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (48,'White Birch Brewing',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (49,'Firestone Walker Brewing Company',76) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (50,'SweetWater Brewing Company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (51,'Flying Mouse Brewery',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (52,'Upslope Brewing Company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (53,'Pipeworks Brewing Company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (54,'Bent Brewstillery',362) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (55,'Flesk Brewing Company',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (56,'Pollyanna Brewing Company',366) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (57,'BuckleDown Brewing',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (58,'Destihl Brewery',98) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (59,'Summit Brewing Company',397) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (60,'Latitude 42 Brewing Company',128) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (61,'4 Hands Brewing Company',111) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (62,'Surly Brewing Company',164) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (63,'Against The Grain Brewery',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (64,'Crazy Mountain Brewing Company',72) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (65,'SlapShot Brewing Company',494) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (66,'Mikerphone Brewing',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (67,'Freetail Brewing Company',418) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (68,'3 Daughters Brewing',520) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (69,'Red Shedman Farm Brewery and Hop...',225) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (70,'Appalachian Mountain Brewery',172) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (71,'Birdsong Brewing Company',379) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (72,'Union Craft Brewing',136) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (73,'Atwater Brewery',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (74,'Ale Asylum',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (75,'Two Brothers Brewing Company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (76,'Bent Paddle Brewing Company',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (77,'Bell''s Brewery',519) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (78,'Blue Owl Brewing',200) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (79,'Speakasy Ales & Lagers',298) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (80,'Black Tooth Brewing Company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (81,'Hopworks Urban Brewery',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (82,'Epic Brewing',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (83,'New Belgium Brewing Company',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (84,'Sierra Nevada Brewing Company',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (85,'Keweenaw Brewing Company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (86,'Brewery Terra Firma',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (87,'Grey Sail Brewing Company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (88,'Kirkwood Station Brewing Company',318) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (89,'Goose Island Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (90,'Broad Brook Brewing LLC',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (91,'The Lion Brewery',338) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (92,'Madtree Brewing Company',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (93,'Jackie O''s Pub & Brewery',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (94,'Rhinegeist Brewery',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (95,'Warped Wing Brewing Company',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (96,'Blackrocks Brewery',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (97,'Catawba Valley Brewing Company',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (98,'Tröegs Brewing Company',191) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (99,'Mission Brewery',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (100,'Christian Moerlein Brewing Company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (101,'West Sixth Brewing',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (102,'Coastal Extreme Brewing Company',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (103,'King Street Brewing Company',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (104,'Beer Works Brewery',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (105,'Lone Tree Brewing Company',310) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (106,'Four String Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (107,'Glabrous Brewing Company',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (108,'Bonfire Brewing Company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (109,'Thomas Hooker Brewing Company',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (110,'Woodstock Inn, Station & Brewery',130) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (111,'Renegade Brewing Company',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (112,'Mother Earth Brew Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (113,'Black Market Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (114,'Vault Brewing Company',508) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (115,'Jailbreak Brewing Company',503) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (116,'Smartmouth Brewing Company',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (117,'Base Camp Brewing Co.',91) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (118,'Alameda Brewing',509) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (119,'Southern Star Brewing Company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (120,'Steamworks Brewing Company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (121,'Horny Goat Brew Pub',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (122,'Cheboygan Brewing Company',83) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (123,'Center of the Universe Brewing C...',75) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (124,'Ipswich Ale Brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (125,'Griffin Claw Brewing Company',149) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (126,'Karbach Brewing Company',336) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (127,'Uncle Billy''s Brewery and Smokeh...',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (128,'Deep Ellum Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (129,'Real Ale Brewing Company',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (130,'Straub Brewery',129) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (131,'Shebeen Brewing Company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (132,'Stevens Point Brewery',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (133,'Weston Brewing Company',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (134,'Southern Prohibition Brewing Com...',544) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (135,'Minhas Craft Brewery',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (136,'Pug Ryan''s Brewery',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (137,'Hops & Grains Brewing Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (138,'Sietsema Orchards and Cider Mill',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (139,'Summit Brewing Company',357) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (140,'Core Brewing & Distilling Company',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (141,'Independence Brewing Company',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (142,'Cigar City Brewing Company',179) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (143,'Third Street Brewhouse',65) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (144,'Narragansett Brewing Company',455) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (145,'Grimm Brothers Brewhouse',436) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (146,'Cisco Brewers',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (147,'Angry Minnow',339) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (148,'Platform Beer Company',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (149,'Odyssey Beerwerks',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (150,'Lonerider Brewing Company',173) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (151,'Oakshire Brewing',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (152,'Fort Pitt Brewing Company',209) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (153,'Tin Roof Brewing Company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (154,'Three Creeks Brewing',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (155,'2 Towns Ciderhouse',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (156,'Caldera Brewing Company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (157,'Greenbrier Valley Brewing Company',341) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (158,'Phoenix Ale Brewery',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (159,'Lumberyard Brewing Company',53) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (160,'Uinta Brewing Company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (161,'Four Peaks Brewing Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (162,'Martin House Brewing Company',103) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (163,'Right Brain Brewery',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (164,'Sly Fox Brewing Company',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (165,'Round Guys Brewing',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (166,'Great Crescent Brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (167,'Oskar Blues Brewery',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (168,'Boxcar Brewing Company',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (169,'High Hops Brewery',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (170,'Crooked Fence Brewing Company',126) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (171,'Everybody''s Brewing',453) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (172,'Anderson Valley Brewing Company',360) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (173,'Fiddlehead Brewing Company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (174,'Evil Twin Brewing',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (175,'New Orleans Lager & Ale Brewing ...',440) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (176,'Spiteful Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (177,'Rahr & Sons Brewing Company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (178,'18th Street Brewery',547) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (179,'Cambridge Brewing Company',95) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (180,'Carolina Brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (181,'Frog Level Brewing Company',417) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (182,'Wild Wolf Brewing Company',199) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (183,'COOP Ale Works',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (184,'Seventh Son Brewing Company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (185,'Oasis Texas Brewing Company',345) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (186,'Vander Mill Ciders',421) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (187,'St. Julian Winery',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (188,'Pedernales Brewing Company',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (189,'Mother''s Brewing',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (190,'Modern Monks Brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (191,'Two beer Brewing Company',548) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (192,'Snake River Brewing Company',302) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (193,'Capital Brewery',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (194,'Anthem Brewing Company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (195,'Goodlife Brewing Co.',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (196,'Breakside Brewery',56) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (197,'Goose Island Brewery Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (198,'Burnside Brewing Co.',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (199,'Hop Valley Brewing Company',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (200,'Worthy Brewing Company',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (201,'Occidental Brewing Company',377) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (202,'Fearless Brewing Company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (203,'Upland Brewing Company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (204,'Mehana Brewing Co.',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (205,'Hawai''i Nui Brewing Co.',117) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (206,'People''s Brewing Company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (207,'Fort George Brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (208,'Branchline Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (209,'Kalona Brewing Company',522) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (210,'Modern Times Beer',158) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (211,'Temperance Beer Company',230) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (212,'Wisconsin Brewing Company',245) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (213,'Crow Peak Brewing Company',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (214,'Grapevine Craft Brewery',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (215,'Buffalo Bayou Brewing Company',115) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (216,'Texian Brewing Co.',260) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (217,'Orpheus Brewing',167) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (218,'Forgotten Boardwalk',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (219,'Laughing Dog Brewing Company',252) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (220,'Bozeman Brewing Company',351) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (221,'Big Choice Brewing',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (222,'Big Storm Brewing Company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (223,'Carton Brewing Company',226) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (224,'Midnight Sun Brewing Company',484) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (225,'Fat Head''s Brewery',67) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (226,'Refuge Brewery',186) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (227,'Chatham Brewing',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (228,'DC Brau Brewing Company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (229,'Geneva Lake Brewing Company',290) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (230,'Rochester Mills Brewing Company',237) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (231,'Cape Ann Brewing Company',159) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (232,'Borderlands Brewing Company',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (233,'College Street Brewhouse and Pub',168) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (234,'Joseph James Brewing Company',287) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (235,'Harpoon Brewery',224) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (236,'Back East Brewing Company',327) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (237,'Champion Brewing Company',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (238,'Devil''s Backbone Brewing Company',481) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (239,'Newburgh Brewing Company',444) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (240,'Wiseacre Brewing Company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (241,'Golden Road Brewing',401) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (242,'New Republic Brewing Company',161) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (243,'Infamous Brewing Company',412) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (244,'Two Henrys Brewing Company',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (245,'Lift Bridge Brewing Company',141) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (246,'Lucky Town Brewing Company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (247,'Quest Brewing Company',187) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (248,'Creature Comforts',144) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (249,'Half Full Brewery',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (250,'Southampton Publick House',394) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (251,'Chapman''s Brewing',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (252,'Barrio Brewing Company',240) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (253,'Santa Cruz Mountain Brewing',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (254,'Frankenmuth Brewery',527) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (255,'Meckley''s Cidery',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (256,'Stillwater Artisanal Ales',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (257,'Finch''s Beer Company',525) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (258,'South Austin Brewery',105) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (259,'Bauhaus Brew Labs',169) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (260,'Ozark Beer Company',553) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (261,'Mountain Town Brewing Company',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (262,'Otter Creek Brewing',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (263,'The Brewer''s Art',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (264,'Denver Beer Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (265,'Ska Brewing Company',540) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (266,'Tractor Brewing Company',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (267,'Peak Organic Brewing Company',478) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (268,'Cape Cod Beer',392) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (269,'Long Trail Brewing Company',231) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (270,'Great Raft Brewing Company',396) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (271,'Alaskan Brewing Company',364) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (272,'Notch Brewing Company',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (273,'The Alchemist',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (274,'Three Notch''d Brewing Company',82) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (275,'Portside Brewery',145) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (276,'Otter Creek Brewing',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (277,'Montauk Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (278,'Indeed Brewing Company',139) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (279,'Berkshire Brewing Company',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (280,'Foolproof Brewing Company',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (281,'Headlands Brewing Company',365) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (282,'Bolero Snort Brewery',106) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (283,'Thunderhead Brewing Company',404) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (284,'Defiance Brewing Company',284) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (285,'Milwaukee Brewing Company',84) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (286,'Catawba Island Brewing',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (287,'Back Forty Beer Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (288,'Four Corners Brewing Company',60) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (289,'Saint Archer Brewery',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (290,'Rogue Ales',371) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (291,'Hale''s Ales',554) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (292,'Tommyknocker Brewery',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (293,'Baxter Brewing Company',146) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (294,'Northampton Brewery',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (295,'Black Shirt Brewing Company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (296,'Wachusett Brewing Company',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (297,'Widmer Brothers Brewing Company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (298,'Hop Farm Brewing Company',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (299,'Liquid Hero Brewery',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (300,'Matt Brewing Company',502) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (301,'Boston Beer Company',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (302,'Old Forge Brewing Company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (303,'Utah Brewers Cooperative',152) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (304,'Magic Hat Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (305,'Blue Hills Brewery',464) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (306,'Night Shift Brewing',555) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (307,'Beach Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (308,'Payette Brewing Company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (309,'Brew Bus Brewing',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (310,'Sockeye Brewing Company',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (311,'Pine Street Brewery',109) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (312,'Dirty Bucket Brewing Company',390) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (313,'Jackalope Brewing Company',543) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (314,'Slanted Rock Brewing Company',479) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (315,'Piney River Brewing Company',477) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (316,'Cutters Brewing Company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (317,'Iron Hill Brewery & Restaurant',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (318,'Marshall Wharf Brewing Company',316) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (319,'Banner Beer Company',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (320,'Dick''s Brewing Company',68) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (321,'Claremont Craft Ales',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (322,'Rivertown Brewing Company',420) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (323,'Voodoo Brewery',189) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (324,'D.L. Geary Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (325,'Pisgah Brewing Company',108) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (326,'Neshaminy Creek Brewing Company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (327,'Morgan Street Brewery',250) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (328,'Half Acre Beer Company',395) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (329,'The Just Beer Project',300) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (330,'The Bronx Brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (331,'Dead Armadillo Craft Brewing',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (332,'Catawba Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (333,'La Cumbre Brewing Company',212) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (334,'David''s Ale Works',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (335,'The Traveler Beer Company',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (336,'Fargo Brewing Company',143) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (337,'Big Sky Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (338,'Nebraska Brewing Company',475) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (339,'Uncle John''s Fruit House Winery',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (340,'Wormtown Brewery',171) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (341,'Due South Brewing Company',359) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (342,'Palisade Brewing Company',458) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (343,'KelSo Beer Company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (344,'Hardywood Park Craft Brewery',487) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (345,'Wolf Hills Brewing Company',292) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (346,'Lavery Brewing Company',62) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (347,'Manzanita Brewing Company',369) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (348,'Fullsteam Brewery',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (349,'Four Horsemen Brewing Company',346) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (350,'Hinterland Brewery',469) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (351,'Central Coast Brewing Company',344) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (352,'Westfield River Brewing Company',536) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (353,'Elevator Brewing Company',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (354,'Aslan Brewing Company',317) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (355,'Kulshan Brewery',86) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (356,'Pikes Peak Brewing Company',155) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (357,'Manayunk Brewing Company',211) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (358,'Buckeye Brewing',207) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (359,'Daredevil Brewing Company',551) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (360,'NoDa Brewing Company',238) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (361,'Aviator Brewing Company',498) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (362,'Wild Onion Brewing Company',326) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (363,'Hilliard''s Beer',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (364,'Mikkeller',463) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (365,'Bohemian Brewery',500) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (366,'Great River Brewery',480) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (367,'Mustang Brewing Company',529) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (368,'Airways Brewing Company',101) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (369,'21st Amendment Brewery',387) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (370,'Eddyline Brewery & Restaurant',320) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (371,'Pizza Port Brewing Company',473) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (372,'Sly Fox Brewing Company',425) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (373,'Spring House Brewing Company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (374,'7venth Sun',465) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (375,'Astoria Brewing Company',403) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (376,'Maui Brewing Company',104) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (377,'RoughTail Brewing Company',376) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (378,'Lucette Brewing Company',373) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (379,'Bold City Brewery',107) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (380,'Grey Sail Brewing of Rhode Island',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (381,'Blue Blood Brewing Company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (382,'Swashbuckler Brewing Company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (383,'Blue Mountain Brewery',193) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (384,'Starr Hill Brewery',213) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (385,'Westbrook Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (386,'Shipyard Brewing Company',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (387,'Revolution Brewing',504) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (388,'Natian Brewery',174) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (389,'Alltech''s Lexington Brewing Company',270) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (390,'Oskar Blues Brewery (North Carol...',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (391,'Orlison Brewing Company',73) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (392,'Breckenridge Brewery',323) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (393,'Santa Fe Brewing Company',490) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (394,'Miami Brewing Company',219) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (395,'Schilling & Company',333) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (396,'Hops & Grain Brewery',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (397,'White Flame Brewing Company',266) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (398,'Ruhstaller Beer Company',55) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (399,'Saugatuck Brewing Company',331) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (400,'Moab Brewery',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (401,'Macon Beer Company',356) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (402,'Amnesia Brewing Company',255) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (403,'Wolverine State Brewing Company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (404,'Red Tank Cider Company',175) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (405,'Cascadia Ciderworks United',194) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (406,'Fate Brewing Company',93) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (407,'Lazy Monk Brewing',335) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (408,'Bitter Root Brewing',201) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (409,'10 Barrel Brewing Company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (410,'Tamarack Brewing Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (411,'New England Brewing Company',236) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (412,'Seattle Cider Company',467) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (413,'Straight to Ale',533) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (414,'Austin Beerworks',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (415,'Blue Mountain Brewery',517) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (416,'Coastal Empire Beer Company',514) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (417,'Jack''s Hard Cider (Hauser Estate...',120) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (418,'Boulder Beer Company',497) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (419,'Coalition Brewing Company',405) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (420,'Sanitas Brewing Company',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (421,'Gore Range Brewery',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (422,'Redstone Meadery',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (423,'Blue Dog Mead',288) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (424,'Hess Brewing Company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (425,'Wynkoop Brewing Company',496) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (426,'Ciderboys',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (427,'Armadillo Ale Works',234) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (428,'Roanoke Railhouse Brewery',534) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (429,'Schlafly Brewing Company',307) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (430,'Asher Brewing Company',456) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (431,'Lost Rhino Brewing Company',363) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (432,'North Country Brewing Company',460) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (433,'Seabright Brewery',125) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (434,'French Broad Brewery',220) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (435,'Angry Orchard Cider Company',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (436,'Two Roads Brewing Company',530) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (437,'Southern Oregon Brewing Company',248) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (438,'Brooklyn Brewery',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (439,'The Right Brain Brewery',454) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (440,'Kona Brewing Company',289) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (441,'MillKing It Productions',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (442,'Pateros Creek Brewing Company',505) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (443,'O''Fallon Brewery',386) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (444,'Marble Brewery',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (445,'Big Wood Brewery',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (446,'Howard Brewing Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (447,'Downeast Cider House',165) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (448,'Swamp Head Brewery',486) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (449,'Mavericks Beer Company',259) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (450,'TailGate Beer',261) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (451,'Northwest Brewing Company',176) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (452,'Dad & Dude''s Breweria',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (453,'Centennial Beer Company',435) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (454,'Denali Brewing Company',257) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (455,'Deschutes Brewery',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (456,'Sunken City Brewing Company',273) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (457,'Lucette Brewing Company',398) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (458,'The Black Tooth Brewing Company',137) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (459,'Kenai River Brewing Company',116) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (460,'River North Brewery',277) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (461,'Fremont Brewing Company',267) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (462,'Armstrong Brewing Company',485) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (463,'AC Golden Brewing Company',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (464,'Big Bend Brewing Company',303) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (465,'Good Life Brewing Company',265) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (466,'Engine 15 Brewing',112) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (467,'Green Room Brewing',180) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (468,'Brindle Dog Brewing Company',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (469,'Peace Tree Brewing Company',218) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (470,'Terrapin Brewing Company',361) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (471,'Pete''s Brewing Company',244) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (472,'Okoboji Brewing Company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (473,'Crystal Springs Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (474,'Engine House 9',99) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (475,'Tonka Beer Company',329) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (476,'Red Hare Brewing Company',185) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (477,'Hangar 24 Craft Brewery',314) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (478,'Big Elm Brewing',163) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (479,'Good People Brewing Company',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (480,'Heavy Seas Beer',407) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (481,'Telluride Brewing Company',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (482,'7 Seas Brewing Company',400) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (483,'Confluence Brewing Company',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (484,'Bale Breaker Brewing Company',488) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (485,'The Manhattan Brewing Company',87) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (486,'MacTarnahans Brewing Company',142) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (487,'Stillmank Beer Company',208) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (488,'Redhook Brewery',451) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (489,'Dock Street Brewery',160) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (490,'Blue Point Brewing Company',439) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (491,'Tampa Bay Brewing Company',59) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (492,'Devil''s Canyon Brewery',79) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (493,'Stone Coast Brewing Company',271) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (494,'Broken Tooth Brewing Company',275) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (495,'Seven Brides Brewery',495) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (496,'Newburyport Brewing Company',256) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (497,'Dry Dock Brewing Company',347) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (498,'Cans Bar and Canteen',162) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (499,'Sprecher Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (500,'Wildwood Brewing Company',337) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (501,'High Noon Saloon And Brewery',352) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (502,'Woodchuck Hard Cider',450) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (503,'Sea Dog Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (504,'Oskar Blues Brewery',549) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (505,'Carolina Beer & Beverage',77) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (506,'Krebs Brewing Company (Pete''s Pl...',114) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (507,'Warbird Brewing Company',61) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (508,'Mudshark Brewing Company',280) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (509,'Spilker Ales',178) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (510,'Wingman Brewers',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (511,'Kettle House Brewing Company',430) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (512,'Sherwood Forest Brewers',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (513,'Cottrell Brewing',426) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (514,'Arctic Craft Brewery',434) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (515,'Monkey Paw Pub & Brewery',383) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (516,'Crabtree Brewing Company',368) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (517,'Emerald City Beer Company',515) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (518,'Butcher''s Brewing',301) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (519,'New South Brewing Company',262) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (520,'Big River Brewing Company',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (521,'Twisted Pine Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (522,'Flying Dog Brewery',188) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (523,'Uncommon Brewers',58) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (524,'Aspen Brewing Company',57) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (525,'Triangle Brewing Company',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (526,'Bomb Beer Company',85) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (527,'Churchkey Can Company',399) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (528,'Intuition Ale Works',518) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (529,'Asheville Brewing Company',124) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (530,'Northwoods Brewpub',433) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (531,'Buckbean Brewing Company',306) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (532,'Dolores River Brewery',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (533,'Flat Rock Brewing Company',506) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (534,'Abita Brewing Company',94) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (535,'Mammoth Brewing Company',349) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (536,'Harvest Moon Brewing Company',81) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (537,'Grand Canyon Brewing Company',297) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (538,'Lewis and Clark Brewing Company',448) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (539,'Dundee Brewing Company',324) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (540,'Twin Lakes Brewing Company',294) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (541,'Mother Earth Brewing Company',438) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (542,'Arcadia Brewing Company',205) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (543,'Angry Minnow Brewing Company',355) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (544,'Great Northern Brewing Company',521) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (545,'Pyramid Breweries',177) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (546,'Lancaster Brewing Company',411) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (547,'Upstate Brewing Company',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (548,'Moat Mountain Smoke House & Brew...',431) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (549,'Prescott Brewing Company',512) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (550,'Mogollon Brewing Company',239) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (551,'Wind River Brewing Company',388) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (552,'Silverton Brewery',472) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (553,'Mickey Finn''s Brewery',427) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (554,'Covington Brewhouse',461) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (555,'Dave''s Brewfarm',74) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (556,'Ukiah Brewing Company',511) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (557,'Butternuts Beer and Ale',268) ON CONFLICT DO NOTHING;
INSERT INTO beer.breweries(id,name,city_id) VALUES (558,'Sleeping Lady Brewing Company',7) ON CONFLICT DO NOTHING;
