CREATE TABLE IF NOT EXISTS beer.cities(
   id       INTEGER  NOT NULL PRIMARY KEY,
   name     VARCHAR(19) NOT NULL,
   state_id INTEGER NOT NULL references beer.states (id),
   created_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc'),
   updated_at TIMESTAMP without TIME ZONE DEFAULT (now() at time zone 'utc')
);
    SELECT beer.trigger_creation('beer','beer.cities','tr_b_cities');
INSERT INTO beer.cities(id,name,state_id) VALUES (1,'Minneapolis',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (2,'Louisville',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (3,'Framingham',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (4,'San Diego',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (5,'San Francisco',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (6,'Charleston',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (7,'Denver',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (8,'Bridgman',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (9,'Holland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (10,'Grand Rapids',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (11,'Grand Rapids',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (12,'Petoskey',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (13,'Marquette',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (14,'Comstock Park',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (15,'South Lyon',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (16,'Grand Rapids',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (17,'Indianapolis',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (18,'Evansville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (19,'Indianapolis',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (20,'Plainfield',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (21,'Granger',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (22,'Martinsville',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (23,'Valparaiso',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (24,'Indianapolis',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (25,'Michigan City',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (26,'Indianapolis',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (27,'Mishawaka',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (28,'Columbus',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (29,'Bargersville',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (30,'Seven Points',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (31,'Chandler',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (32,'Kansas City',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (33,'Stevens Point',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (34,'Torrance',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (35,'San Diego',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (36,'San Francisco',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (37,'Buellton',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (38,'Boulder',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (39,'Dripping Springs',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (40,'Kalamazoo',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (41,'Murphysboro',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (42,'East Fairfield',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (43,'Portland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (44,'Export',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (45,'Chicago',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (46,'Manhattan',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (47,'Brooklyn',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (48,'Hooksett',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (49,'Paso Robles',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (50,'Atlanta',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (51,'Troutville',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (52,'Boulder',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (53,'Chicago',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (54,'Roseville',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (55,'Lombard',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (56,'Lemont',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (57,'Lyons',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (58,'Bloomington',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (59,'St. Paul',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (60,'Portage',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (61,'Saint Louis',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (62,'Brooklyn Center',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (63,'Louisville',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (64,'Edwards',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (65,'Chicago',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (66,'Chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (67,'San Antonio',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (68,'St Petersburg',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (69,'Mt. Airy',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (70,'Boone',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (71,'Charlotte',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (72,'Baltimore',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (73,'Detroit',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (74,'Madison',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (75,'Warrenville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (76,'Duluth',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (77,'Kalamazoo',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (78,'Austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (79,'San Francisco',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (80,'Sheridan',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (81,'Portland',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (82,'Denver',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (83,'Fort Collins',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (84,'Chico',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (85,'Houghton',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (86,'Traverse City',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (87,'Westerly',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (88,'Kirkwood',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (89,'Chicago',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (90,'East Windsor',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (91,'Wilkes-Barre',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (92,'Cincinnati',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (93,'Athens',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (94,'Cincinnati',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (95,'Dayton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (96,'Marquette',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (97,'Morganton',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (98,'Hershey',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (99,'San Diego',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (100,'Cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (101,'Lexington',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (102,'Newport',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (103,'Anchorage',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (104,'Lowell',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (105,'Lone Tree',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (106,'Columbus',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (107,'Pineland',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (108,'Eagle',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (109,'Bloomfield',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (110,'North Woodstock',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (111,'Denver',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (112,'Vista',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (113,'Temecula',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (114,'Yardley',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (115,'Laurel',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (116,'Norfolk',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (117,'Portland',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (118,'Portland',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (119,'Conroe',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (120,'Durango',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (121,'Milwaukee',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (122,'Cheboygan',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (123,'Ashland',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (124,'Ipswich',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (125,'Birmingham',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (126,'Houston',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (127,'Austin',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (128,'Dallas',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (129,'Blanco',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (130,'St Mary''s',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (131,'Wolcott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (132,'Stevens Point',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (133,'Weston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (134,'Hattiesburg',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (135,'Monroe',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (136,'Dillon',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (137,'Austin',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (138,'Ada',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (139,'St Paul',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (140,'Springdale',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (141,'Austin',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (142,'Tampa',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (143,'Cold Spring',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (144,'Providence',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (145,'Loveland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (146,'Nantucket',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (147,'Hayward',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (148,'Cleveland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (149,'Arvada',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (150,'Raleigh',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (151,'Eugene',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (152,'Latrobe',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (153,'Baton Rouge',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (154,'Sisters',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (155,'Corvallis',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (156,'Ashland',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (157,'Lewisburg',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (158,'Phoenix',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (159,'Flagstaff',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (160,'Salt Lake City',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (161,'Tempe',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (162,'Fort Worth',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (163,'Traverse City',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (164,'Phoenixville',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (165,'Lansdale',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (166,'Aurora',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (167,'Longmont',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (168,'West Chester',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (169,'Windsor',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (170,'Garden City',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (171,'White Salmon',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (172,'Boonville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (173,'Shelburne',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (174,'Brooklyn',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (175,'New Orleans',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (176,'Chicago',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (177,'Fort Worth',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (178,'Gary',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (179,'Cambridge',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (180,'Pittsboro',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (181,'Waynesville',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (182,'Nellysford',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (183,'Oklahoma City',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (184,'Columbus',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (185,'Austin',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (186,'Spring Lake',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (187,'Paw Paw',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (188,'Fredericksburg',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (189,'Springfield',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (190,'Lincoln',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (191,'Seattle',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (192,'Jackson',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (193,'Middleton',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (194,'Oklahoma City',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (195,'Bend',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (196,'Portland',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (197,'Chicago',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (198,'Portland',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (199,'Springfield',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (200,'Bend',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (201,'Portland',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (202,'Estacada',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (203,'Bloomington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (204,'Hilo',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (205,'Hilo',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (206,'Lafayette',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (207,'Astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (208,'San Antonio',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (209,'Kalona',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (210,'San Diego',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (211,'Evanston',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (212,'Verona',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (213,'Spearfish',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (214,'Farmers Branch',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (215,'Houston',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (216,'Richmond',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (217,'Atlanta',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (218,'Cherry Hill',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (219,'Ponderay',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (220,'Bozeman',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (221,'Broomfield',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (222,'Odessa',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (223,'Atlantic Highlands',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (224,'Anchorage',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (225,'Middleburg Heights',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (226,'Temecula',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (227,'Chatham',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (228,'Washington',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (229,'Lake Geneva',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (230,'Rochester',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (231,'Gloucester',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (232,'Tucson',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (233,'Lake Havasu City',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (234,'Henderson',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (235,'Boston',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (236,'Bloomfield',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (237,'Charlottesville',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (238,'Lexington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (239,'Newburgh',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (240,'Memphis',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (241,'Los Angeles',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (242,'College Station',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (243,'Austin',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (244,'Plant City',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (245,'Stillwater',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (246,'Jackson',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (247,'Greenville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (248,'Athens',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (249,'Stamford',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (250,'Southampton',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (251,'Angola',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (252,'Tucson',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (253,'Santa Cruz',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (254,'Frankenmuth',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (255,'Somerset Center',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (256,'Baltimore',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (257,'Chicago',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (258,'South Austin',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (259,'Minneapolis',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (260,'Rogers',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (261,'Mount Pleasant',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (262,'Waterbury',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (263,'Baltimore',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (264,'Denver',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (265,'Durango',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (266,'Albuquerque',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (267,'Portland',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (268,'Hyannis',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (269,'Bridgewater Corners',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (270,'Shreveport',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (271,'Juneau',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (272,'Ipswich',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (273,'Waterbury',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (274,'Charlottesville',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (275,'Cleveland',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (276,'Middlebury',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (277,'Montauk',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (278,'Minneapolis',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (279,'South Deerfield',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (280,'Pawtucket',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (281,'Mill Valley',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (282,'Ridgefield Park',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (283,'Kearney',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (284,'Hays',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (285,'Milwaukee',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (286,'Port Clinton',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (287,'Gadsden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (288,'Dallas',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (289,'San Diego',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (290,'Newport',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (291,'Seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (292,'Idaho Springs',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (293,'Lewiston',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (294,'Northamtpon',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (295,'Denver',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (296,'Westminster',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (297,'Portland',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (298,'Pittsburgh',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (299,'York',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (300,'Utica',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (301,'Boston',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (302,'Danville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (303,'Salt Lake City',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (304,'South Burlington',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (305,'Canton',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (306,'Everett',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (307,'Virginia Beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (308,'Garden City',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (309,'Tampa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (310,'Boise',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (311,'San Francisco',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (312,'Woodinville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (313,'Nashville',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (314,'Meridian',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (315,'Bucryus',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (316,'Avon',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (317,'Wilmington',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (318,'Belfast',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (319,'Williamsburg',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (320,'Centralia',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (321,'Claremont',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (322,'Lockland',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (323,'Meadville',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (324,'Portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (325,'Black Mountain',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (326,'Croydon',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (327,'Saint Louis',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (328,'Chicago',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (329,'Burlington',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (330,'Bronx',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (331,'Tulsa',9) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (332,'Morganton',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (333,'Albuquerque',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (334,'Diamond Springs',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (335,'Burlington',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (336,'Fargo',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (337,'Missoula',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (338,'Papillion',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (339,'St. John''s',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (340,'Worcester',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (341,'Boynton Beach',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (342,'Palisade',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (343,'Brooklyn',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (344,'Richmond',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (345,'Abingdon',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (346,'Erie',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (347,'Santee',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (348,'Durham',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (349,'South Bend',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (350,'Green Bay',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (351,'San Luis Obispo',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (352,'Westfield',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (353,'Columbus',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (354,'Bellingham',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (355,'Bellingham',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (356,'Monument',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (357,'Philadelphia',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (358,'Cleveland',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (359,'Shelbyville',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (360,'Charlotte',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (361,'Fuquay-Varina',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (362,'Lake Barrington',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (363,'Seattle',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (364,'Pottstown',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (365,'Midvale',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (366,'Davenport',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (367,'Mustang',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (368,'Kent',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (369,'San Francisco',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (370,'Buena Vista',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (371,'Carlsbad',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (372,'Pottstown',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (373,'Conestoga',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (374,'Dunedin',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (375,'Astoria',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (376,'Lahaina',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (377,'Midwest City',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (378,'Menominee',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (379,'Jacksonville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (380,'Westerly',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (381,'Lincoln',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (382,'Manheim',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (383,'Afton',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (384,'Crozet',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (385,'Mt. Pleasant',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (386,'Portland',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (387,'Paonia',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (388,'Portland',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (389,'Lexington',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (390,'Brevard',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (391,'Airway Heights',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (392,'Denver',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (393,'Santa Fe',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (394,'Miami',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (395,'Seattle',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (396,'Austin',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (397,'Hudsonville',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (398,'Sacramento',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (399,'Douglas',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (400,'Moab',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (401,'Macon',10) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (402,'Washougal',25) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (403,'Ann Arbor',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (404,'Bend',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (405,'Portland',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (406,'Boulder',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (407,'Eau Claire',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (408,'Hamilton',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (409,'Bend',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (410,'Lakeside',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (411,'Woodbridge',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (412,'Seattle',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (413,'Huntsville',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (414,'Austin',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (415,'Arrington',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (416,'Savannah',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (417,'Biglerville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (418,'Boulder',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (419,'Portland',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (420,'Boulder',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (421,'Edwards',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (422,'Boulder',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (423,'Eugene',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (424,'San Diego',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (425,'Denver',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (426,'Stevens Point',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (427,'Denton',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (428,'Roanoke',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (429,'Saint Louis',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (430,'Boulder',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (431,'Ashburn',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (432,'Slippery Rock',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (433,'Santa Cruz',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (434,'Asheville',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (435,'Cincinnati',47) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (436,'Stratford',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (437,'Medford',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (438,'Brooklyn',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (439,'Traverse City',17) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (440,'Kona',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (441,'Royal Oak',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (442,'Fort Collins',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (443,'O''Fallon',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (444,'Albuquerque',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (445,'Vadnais Heights',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (446,'Lenoir',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (447,'Leominster',46) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (448,'Gainesville',48) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (449,'Half Moon Bay',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (450,'San Diego',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (451,'Pacific',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (452,'Aurora',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (453,'Edwards',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (454,'Talkeetna',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (455,'Bend',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (456,'Hardy',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (457,'Menominie',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (458,'Sheridan',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (459,'Soldotna',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (460,'Denver',49) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (461,'Seattle',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (462,'South San Francisco',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (463,'Golden',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (464,'Alpine',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (465,'Bend',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (466,'Jacksonville Beach',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (467,'Jacksonville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (468,'Tampa Bay',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (469,'Knoxville',11) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (470,'Athens',6) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (471,'San Antonio',1) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (472,'Spirit Lake',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (473,'Boulder',14) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (474,'Tacoma',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (475,'Minnetonka',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (476,'Marietta',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (477,'Redlands',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (478,'Sheffield',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (479,'Birmingham',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (480,'Halethorpe',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (481,'Telluride',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (482,'Gig Harbor',34) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (483,'Des Moines',26) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (484,'Yakima',38) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (485,'New York',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (486,'Portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (487,'Green Bay',29) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (488,'Woodinville',42) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (489,'Philadelphia',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (490,'Patchogue',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (491,'Tampa',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (492,'Belmont',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (493,'Portland',44) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (494,'Anchorage',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (495,'Silverton',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (496,'Newburyport',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (497,'Aurora',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (498,'Charlotte',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (499,'Glendale',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (500,'Stevensville',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (501,'Leavenworth',41) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (502,'Middlebury',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (503,'Portland',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (504,'Lyons',30) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (505,'Mooresville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (506,'Krebs',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (507,'Fort Wayne',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (508,'Lake Havasu City',45) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (509,'Cortland',21) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (510,'Tacoma',2) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (511,'Missoula',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (512,'Marlborough',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (513,'Pawcatuck',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (514,'Colorado Springs',4) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (515,'San Diego',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (516,'Greeley',40) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (517,'Seattle',5) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (518,'Carlsbad',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (519,'Myrtle Beach',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (520,'Chattanooga',24) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (521,'Boulder',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (522,'Frederick',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (523,'Santa Cruz',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (524,'Aspen',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (525,'Durham',43) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (526,'New York',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (527,'Seattle',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (528,'Jacksonville',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (529,'Asheville',50) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (530,'Eau Claire',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (531,'Reno',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (532,'Dolores',51) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (533,'Smithton',27) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (534,'Abita Springs',13) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (535,'Mammoth Lakes',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (536,'Belt',39) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (537,'Williams',32) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (538,'Helena',35) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (539,'Rochester',31) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (540,'Greenville',52) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (541,'Kinston',36) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (542,'Battle Creek',28) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (543,'Hayward',33) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (544,'Whitefish',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (545,'Seattle',37) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (546,'Lancaster',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (547,'Elmira',12) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (548,'North Conway',18) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (549,'Prescott',16) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (550,'Flagstaff',3) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (551,'Pinedale',20) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (552,'Silverton',8) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (553,'Libertyville',7) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (554,'Covington',22) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (555,'Wilson',15) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (556,'Ukiah',19) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (557,'Garrattsville',23) ON CONFLICT DO NOTHING;
INSERT INTO beer.cities(id,name,state_id) VALUES (558,'Anchorage',17) ON CONFLICT DO NOTHING;